// register
export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCEEDED = "REGISTER_USER_SUCCEEDED";
export const REGISTER_USER_FAILED = "REGISTER_USER_FAILED";
// == login
export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCEEDED = "LOGIN_USER_SUCCEEDED";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";

// == logout
export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST";
export const LOGOUT_USER_SUCCEEDED = "LOGOUT_USER_SUCCEEDED";
export const LOGOUT_USER_FAILED = "LOGOUT_USER_FAILED";

